# Generated by Django 4.2.27 on 2025-12-19 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Téléphone"
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Sujet")),
                ("message", models.TextField(verbose_name="Message")),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Supprimé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de Contact",
                "verbose_name_plural": "Demandes de Contact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConstructionLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom Complet")),
                ("phone", models.CharField(max_length=50, verbose_name="Téléphone")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "has_land",
                    models.BooleanField(
                        default=False, verbose_name="Possède un Terrain"
                    ),
                ),
                (
                    "location_of_land",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Localisation du Terrain",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Détails supplémentaires du client",
                        verbose_name="Message",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Nouveau"),
                            ("CONTACTED", "Contacté"),
                            ("CONVERTED", "Converti"),
                            ("LOST", "Perdu"),
                        ],
                        default="NEW",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes de suivi par l'équipe",
                        verbose_name="Notes Internes",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Supprimé par",
                    ),
                ),
                (
                    "interested_in",
                    models.ForeignKey(
                        blank=True,
                        help_text="Quel projet du portfolio a attiré ce lead",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="marketing.portfolioitem",
                        verbose_name="Intéressé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Construction",
                "verbose_name_plural": "Leads Construction",
                "ordering": ["-created_at"],
            },
        ),
    ]
