# Generated by Django 4.2.7 on 2026-01-01 12:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0003_alter_activeproject_current_phase"),
        ("billing", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="advance_payment",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant déjà payé par le client (en FCFA)",
                max_digits=15,
                verbose_name="6️⃣ Acompte Versé",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(
                help_text="Date limite de paiement", verbose_name="4️⃣ Date d'Échéance"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Date de création de la facture",
                verbose_name="3️⃣ Date d'Émission",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("CASH", "Espèces"),
                    ("TRANSFER", "Virement"),
                    ("CHECK", "Chèque"),
                ],
                default="CASH",
                help_text="Comment le client va payer",
                max_length=20,
                verbose_name="7️⃣ Mode de Paiement",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="project",
            field=models.ForeignKey(
                help_text="Sélectionnez le projet du client",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="clients.activeproject",
                verbose_name="1️⃣ Projet Client",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("SENT", "Envoyé"),
                    ("PAID", "Payé"),
                    ("OVERDUE", "En Retard"),
                    ("CANCELLED", "Annulé"),
                ],
                default="DRAFT",
                help_text="Brouillon par défaut",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="subject",
            field=models.CharField(
                help_text="Ex: Construction villa, Plan et suivi, Travaux de finition...",
                max_length=255,
                verbose_name="2️⃣ Objet de la Facture",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tax_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Ex: 19 pour 19% de TVA (0 si pas de TVA)",
                max_digits=5,
                verbose_name="5️⃣ TVA (%)",
            ),
        ),
    ]
