# Generated by Django 4.2.7 on 2026-01-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "billing",
            "0003_alter_invoice_advance_payment_alter_invoice_due_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="tax_type",
            field=models.CharField(
                choices=[
                    ("NONE", "Aucune Taxe"),
                    ("ISB", "ISB (-2%)"),
                    ("TVA", "TVA (+5%)"),
                    ("CUSTOM", "Taux Personnalisé"),
                ],
                default="NONE",
                help_text="Choisissez le type de taxe à appliquer",
                max_length=20,
                verbose_name="Type de Taxe",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tax_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Auto-rempli selon le type (ISB=-2, TVA=+5). Modifiable pour taux personnalisé",
                max_digits=5,
                verbose_name="5️⃣ Taux de Taxe (%)",
            ),
        ),
    ]
