# Generated by Django 4.2.7 on 2025-12-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectupdate",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Lien YouTube, Vimeo ou autre (optionnel)",
                verbose_name="Lien Vidéo",
            ),
        ),
        migrations.AlterField(
            model_name="activeproject",
            name="current_phase",
            field=models.CharField(
                choices=[
                    ("FONDATION", "Fondation"),
                    ("ELEVATION", "Élévation"),
                    ("PREP_DALLE", "Préparation dalle"),
                    ("COULAGE_DALLE", "Coulage de la dalle"),
                    ("DECOFFRAGE_DALLE", "Décoffrage de la dalle"),
                    ("CRÉPISSAGES", "Crépissages"),
                    ("FINITION", "Finition"),
                ],
                default="FONDATION",
                max_length=20,
                verbose_name="Phase Actuelle",
            ),
        ),
        migrations.AlterField(
            model_name="projectupdate",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Télécharger une photo du chantier",
                null=True,
                upload_to="projects/updates/",
                verbose_name="Photo du Chantier",
            ),
        ),
    ]
