# Generated by Django 4.2.7 on 2026-01-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_add_video_url_to_project_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activeproject",
            name="current_phase",
            field=models.CharField(
                choices=[
                    ("CONCEPTION", "Conception et Démarches"),
                    ("IMPLANTATION", "Implantation"),
                    ("FONDATIONS", "Fondations"),
                    ("ELEVATION_MURS", "Élévation des Murs"),
                    ("DALLE", "Dalle et Acrotère"),
                    ("CREPISSAGE", "Crépissage"),
                    ("ELECTRICITE_PLOMBERIE", "Électricité & Plomberie"),
                    ("RESEAUX", "Réseaux et Sécurité"),
                    ("CARRELAGE_PLAFOND", "Carrelage & Plafonnage"),
                    ("PEINTURE_MENUISERIE", "Peinture & Menuiserie"),
                    ("EXTERIEUR", "Aménagements Extérieurs"),
                ],
                default="CONCEPTION",
                max_length=30,
                verbose_name="Phase Actuelle",
            ),
        ),
    ]
